package gameStore.dataModel.product;

public enum Genre {
    ACTION, ADVENTURE, ARCADE, BATTLE_ROYAL, EDUCATIONAL, FIGHTING, HORROR, INTERACTIVE_FICTION, MMORPG, OTHER,
    PLATFORM, PUZZLE, QUEST, RACING, RPG, RTS, SHOOTER, SIMULATOR,
    SPORT, STRATEGY, TABLETOP;
}
